sudo: required
dist: trusty

install:
  - env
  - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes python-virtualenv liberasurecode-dev libssl-dev libattr1-dev keystone
  - virtualenv $HOME/venv
  - source $HOME/venv/bin/activate
  - pip install --upgrade pip setuptools virtualenv tox
  - cd ..
  - git clone -b stable/ocata https://github.com/openstack/swift.git
  - cd swift
  - python setup.py install
  - pip install --upgrade -r requirements.txt
  - cd ..
  - cd swift3
  - pip install --upgrade -r requirements.txt
  - pip install --upgrade -r test-requirements.txt

script:
  - set -e
  - tox
